"""Add document models adjusted

Revision ID: 13f5ece46d45
Revises: 233ca1816025
Create Date: 2025-04-01 22:03:02.229640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import mysql # Keep removed

# revision identifiers, used by Alembic.
revision: str = '13f5ece46d45'
down_revision: Union[str, None] = '233ca1816025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to be empty ###
    # The models should now match the existing database schema.
    # This migration serves mainly to mark the schema as up-to-date.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to be empty ###
    # Reverting this is complex and unnecessary if upgrade does nothing.
    pass
    # ### end Alembic commands ###
