version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-wisdom-api
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "443:443"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - GATEWAY_URL=http://localhost:5000
      - FRONTEND_URL=http://localhost:3000
      - GUNICORN_WORKERS=4
      - GUNICORN_LOG_LEVEL=info
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=wisdom_user
      - DB_PASSWORD=wisdom_password
      - DB_NAME=wisdom_db
      - DB_POOL_SIZE=10
      - JWT_SECRET=${JWT_SECRET}
      - SSL_CERTFILE=/etc/ssl/certs/cert.pem
      - SSL_KEYFILE=/etc/ssl/private/key.pem
    volumes:
      - ./.env:/app/.env:ro
      - ./path/to/your/cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./path/to/your/key.pem:/etc/ssl/private/key.pem:ro
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: pdf-wisdom-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: pdf-wisdom-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

volumes:
  redis-data:
  mysql-data:

networks:
  app-network:
    driver: bridge 